spring:
  application:
    name: consumer-kafka-mongodb

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: reservas-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
        schema.registry.url: http://schema-registry:8081
        specific.avro.reader: true

    listener:
      ack-mode: record

  data:
    mongodb:
      uri: mongodb://mongodb:27017/reservasdb
