/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.yasmani.avro.reserva.v1;
@org.apache.avro.specific.AvroGenerated
public enum CanalConfirmacion implements org.apache.avro.generic.GenericEnumSymbol<CanalConfirmacion> {
  WEB, MOBILE, CALL_CENTER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CanalConfirmacion\",\"namespace\":\"org.yasmani.avro.reserva.v1\",\"symbols\":[\"WEB\",\"MOBILE\",\"CALL_CENTER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
