/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.yasmani.avro.reserva.v1;
@org.apache.avro.specific.AvroGenerated
public enum EstadoReserva implements org.apache.avro.generic.GenericEnumSymbol<EstadoReserva> {
  CREADA  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EstadoReserva\",\"namespace\":\"org.yasmani.avro.reserva.v1\",\"symbols\":[\"CREADA\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
