/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.yasmani.avro.reserva.v1;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Evento emitido cuando se crea una reserva */
@org.apache.avro.specific.AvroGenerated
public class ReservaCreada extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2943916660754985504L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReservaCreada\",\"namespace\":\"org.yasmani.avro.reserva.v1\",\"doc\":\"Evento emitido cuando se crea una reserva\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\",\"doc\":\"Identificador único del evento\"},{\"name\":\"reservationId\",\"type\":\"string\",\"doc\":\"Identificador de la reserva\"},{\"name\":\"clienteId\",\"type\":\"string\",\"doc\":\"Identificador del cliente\"},{\"name\":\"fechaReserva\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Fecha de creación de la reserva\"},{\"name\":\"estado\",\"type\":{\"type\":\"enum\",\"name\":\"EstadoReserva\",\"symbols\":[\"CREADA\"]},\"default\":\"CREADA\"},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}],\"doc\":\"Metadatos adicionales del evento\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ReservaCreada> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReservaCreada> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ReservaCreada> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ReservaCreada> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ReservaCreada> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ReservaCreada to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ReservaCreada from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ReservaCreada instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ReservaCreada fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Identificador único del evento */
  private java.lang.CharSequence eventId;
  /** Identificador de la reserva */
  private java.lang.CharSequence reservationId;
  /** Identificador del cliente */
  private java.lang.CharSequence clienteId;
  /** Fecha de creación de la reserva */
  private java.time.Instant fechaReserva;
  private org.yasmani.avro.reserva.v1.EstadoReserva estado;
  /** Metadatos adicionales del evento */
  private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReservaCreada() {}

  /**
   * All-args constructor.
   * @param eventId Identificador único del evento
   * @param reservationId Identificador de la reserva
   * @param clienteId Identificador del cliente
   * @param fechaReserva Fecha de creación de la reserva
   * @param estado The new value for estado
   * @param metadata Metadatos adicionales del evento
   */
  public ReservaCreada(java.lang.CharSequence eventId, java.lang.CharSequence reservationId, java.lang.CharSequence clienteId, java.time.Instant fechaReserva, org.yasmani.avro.reserva.v1.EstadoReserva estado, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata) {
    this.eventId = eventId;
    this.reservationId = reservationId;
    this.clienteId = clienteId;
    this.fechaReserva = fechaReserva.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.estado = estado;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return reservationId;
    case 2: return clienteId;
    case 3: return fechaReserva;
    case 4: return estado;
    case 5: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: reservationId = (java.lang.CharSequence)value$; break;
    case 2: clienteId = (java.lang.CharSequence)value$; break;
    case 3: fechaReserva = (java.time.Instant)value$; break;
    case 4: estado = (org.yasmani.avro.reserva.v1.EstadoReserva)value$; break;
    case 5: metadata = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return Identificador único del evento
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * Identificador único del evento
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'reservationId' field.
   * @return Identificador de la reserva
   */
  public java.lang.CharSequence getReservationId() {
    return reservationId;
  }


  /**
   * Sets the value of the 'reservationId' field.
   * Identificador de la reserva
   * @param value the value to set.
   */
  public void setReservationId(java.lang.CharSequence value) {
    this.reservationId = value;
  }

  /**
   * Gets the value of the 'clienteId' field.
   * @return Identificador del cliente
   */
  public java.lang.CharSequence getClienteId() {
    return clienteId;
  }


  /**
   * Sets the value of the 'clienteId' field.
   * Identificador del cliente
   * @param value the value to set.
   */
  public void setClienteId(java.lang.CharSequence value) {
    this.clienteId = value;
  }

  /**
   * Gets the value of the 'fechaReserva' field.
   * @return Fecha de creación de la reserva
   */
  public java.time.Instant getFechaReserva() {
    return fechaReserva;
  }


  /**
   * Sets the value of the 'fechaReserva' field.
   * Fecha de creación de la reserva
   * @param value the value to set.
   */
  public void setFechaReserva(java.time.Instant value) {
    this.fechaReserva = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'estado' field.
   * @return The value of the 'estado' field.
   */
  public org.yasmani.avro.reserva.v1.EstadoReserva getEstado() {
    return estado;
  }


  /**
   * Sets the value of the 'estado' field.
   * @param value the value to set.
   */
  public void setEstado(org.yasmani.avro.reserva.v1.EstadoReserva value) {
    this.estado = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return Metadatos adicionales del evento
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * Metadatos adicionales del evento
   * @param value the value to set.
   */
  public void setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.metadata = value;
  }

  /**
   * Creates a new ReservaCreada RecordBuilder.
   * @return A new ReservaCreada RecordBuilder
   */
  public static org.yasmani.avro.reserva.v1.ReservaCreada.Builder newBuilder() {
    return new org.yasmani.avro.reserva.v1.ReservaCreada.Builder();
  }

  /**
   * Creates a new ReservaCreada RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReservaCreada RecordBuilder
   */
  public static org.yasmani.avro.reserva.v1.ReservaCreada.Builder newBuilder(org.yasmani.avro.reserva.v1.ReservaCreada.Builder other) {
    if (other == null) {
      return new org.yasmani.avro.reserva.v1.ReservaCreada.Builder();
    } else {
      return new org.yasmani.avro.reserva.v1.ReservaCreada.Builder(other);
    }
  }

  /**
   * Creates a new ReservaCreada RecordBuilder by copying an existing ReservaCreada instance.
   * @param other The existing instance to copy.
   * @return A new ReservaCreada RecordBuilder
   */
  public static org.yasmani.avro.reserva.v1.ReservaCreada.Builder newBuilder(org.yasmani.avro.reserva.v1.ReservaCreada other) {
    if (other == null) {
      return new org.yasmani.avro.reserva.v1.ReservaCreada.Builder();
    } else {
      return new org.yasmani.avro.reserva.v1.ReservaCreada.Builder(other);
    }
  }

  /**
   * RecordBuilder for ReservaCreada instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReservaCreada>
    implements org.apache.avro.data.RecordBuilder<ReservaCreada> {

    /** Identificador único del evento */
    private java.lang.CharSequence eventId;
    /** Identificador de la reserva */
    private java.lang.CharSequence reservationId;
    /** Identificador del cliente */
    private java.lang.CharSequence clienteId;
    /** Fecha de creación de la reserva */
    private java.time.Instant fechaReserva;
    private org.yasmani.avro.reserva.v1.EstadoReserva estado;
    /** Metadatos adicionales del evento */
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.yasmani.avro.reserva.v1.ReservaCreada.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.reservationId)) {
        this.reservationId = data().deepCopy(fields()[1].schema(), other.reservationId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.clienteId)) {
        this.clienteId = data().deepCopy(fields()[2].schema(), other.clienteId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.fechaReserva)) {
        this.fechaReserva = data().deepCopy(fields()[3].schema(), other.fechaReserva);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.estado)) {
        this.estado = data().deepCopy(fields()[4].schema(), other.estado);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.metadata)) {
        this.metadata = data().deepCopy(fields()[5].schema(), other.metadata);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing ReservaCreada instance
     * @param other The existing instance to copy.
     */
    private Builder(org.yasmani.avro.reserva.v1.ReservaCreada other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reservationId)) {
        this.reservationId = data().deepCopy(fields()[1].schema(), other.reservationId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.clienteId)) {
        this.clienteId = data().deepCopy(fields()[2].schema(), other.clienteId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fechaReserva)) {
        this.fechaReserva = data().deepCopy(fields()[3].schema(), other.fechaReserva);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.estado)) {
        this.estado = data().deepCopy(fields()[4].schema(), other.estado);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.metadata)) {
        this.metadata = data().deepCopy(fields()[5].schema(), other.metadata);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * Identificador único del evento
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * Identificador único del evento
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * Identificador único del evento
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * Identificador único del evento
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reservationId' field.
      * Identificador de la reserva
      * @return The value.
      */
    public java.lang.CharSequence getReservationId() {
      return reservationId;
    }


    /**
      * Sets the value of the 'reservationId' field.
      * Identificador de la reserva
      * @param value The value of 'reservationId'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder setReservationId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.reservationId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reservationId' field has been set.
      * Identificador de la reserva
      * @return True if the 'reservationId' field has been set, false otherwise.
      */
    public boolean hasReservationId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reservationId' field.
      * Identificador de la reserva
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder clearReservationId() {
      reservationId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'clienteId' field.
      * Identificador del cliente
      * @return The value.
      */
    public java.lang.CharSequence getClienteId() {
      return clienteId;
    }


    /**
      * Sets the value of the 'clienteId' field.
      * Identificador del cliente
      * @param value The value of 'clienteId'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder setClienteId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.clienteId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'clienteId' field has been set.
      * Identificador del cliente
      * @return True if the 'clienteId' field has been set, false otherwise.
      */
    public boolean hasClienteId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'clienteId' field.
      * Identificador del cliente
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder clearClienteId() {
      clienteId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaReserva' field.
      * Fecha de creación de la reserva
      * @return The value.
      */
    public java.time.Instant getFechaReserva() {
      return fechaReserva;
    }


    /**
      * Sets the value of the 'fechaReserva' field.
      * Fecha de creación de la reserva
      * @param value The value of 'fechaReserva'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder setFechaReserva(java.time.Instant value) {
      validate(fields()[3], value);
      this.fechaReserva = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaReserva' field has been set.
      * Fecha de creación de la reserva
      * @return True if the 'fechaReserva' field has been set, false otherwise.
      */
    public boolean hasFechaReserva() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'fechaReserva' field.
      * Fecha de creación de la reserva
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder clearFechaReserva() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'estado' field.
      * @return The value.
      */
    public org.yasmani.avro.reserva.v1.EstadoReserva getEstado() {
      return estado;
    }


    /**
      * Sets the value of the 'estado' field.
      * @param value The value of 'estado'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder setEstado(org.yasmani.avro.reserva.v1.EstadoReserva value) {
      validate(fields()[4], value);
      this.estado = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'estado' field has been set.
      * @return True if the 'estado' field has been set, false otherwise.
      */
    public boolean hasEstado() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'estado' field.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder clearEstado() {
      estado = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * Metadatos adicionales del evento
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * Metadatos adicionales del evento
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.metadata = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * Metadatos adicionales del evento
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'metadata' field.
      * Metadatos adicionales del evento
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaCreada.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReservaCreada build() {
      try {
        ReservaCreada record = new ReservaCreada();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.reservationId = fieldSetFlags()[1] ? this.reservationId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.clienteId = fieldSetFlags()[2] ? this.clienteId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.fechaReserva = fieldSetFlags()[3] ? this.fechaReserva : (java.time.Instant) defaultValue(fields()[3]);
        record.estado = fieldSetFlags()[4] ? this.estado : (org.yasmani.avro.reserva.v1.EstadoReserva) defaultValue(fields()[4]);
        record.metadata = fieldSetFlags()[5] ? this.metadata : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReservaCreada>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReservaCreada>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReservaCreada>
    READER$ = (org.apache.avro.io.DatumReader<ReservaCreada>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (eventId == null ? 0 : eventId.hashCode());
    result = 31 * result + (reservationId == null ? 0 : reservationId.hashCode());
    result = 31 * result + (clienteId == null ? 0 : clienteId.hashCode());
    result = 31 * result + (fechaReserva == null ? 0 : fechaReserva.hashCode());
    result = 31 * result + (estado == null ? 0 : ((java.lang.Enum) estado).ordinal());
    result = 31 * result + (metadata == null ? 0 : metadata.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ReservaCreada)) {
      return false;
    }
    ReservaCreada other = (ReservaCreada) o;
    if (Utf8.compareSequences(this.eventId, other.eventId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.reservationId, other.reservationId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.clienteId, other.clienteId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.fechaReserva, other.fechaReserva)) {
      return false;
    }
    if (!java.util.Objects.equals(this.estado, other.estado)) {
      return false;
    }
    if (!java.util.Objects.equals(this.metadata, other.metadata)) {
      return false;
    }
    return true;
  }
}










