/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.yasmani.avro.reserva.v1;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Evento emitido cuando una reserva es confirmada */
@org.apache.avro.specific.AvroGenerated
public class ReservaConfirmada extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5767386200099715239L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReservaConfirmada\",\"namespace\":\"org.yasmani.avro.reserva.v1\",\"doc\":\"Evento emitido cuando una reserva es confirmada\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\",\"doc\":\"Identificador único del evento\"},{\"name\":\"reservationId\",\"type\":\"string\",\"doc\":\"Identificador de la reserva\"},{\"name\":\"fechaConfirmacion\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Fecha de confirmación de la reserva\"},{\"name\":\"canalConfirmacion\",\"type\":{\"type\":\"enum\",\"name\":\"CanalConfirmacion\",\"symbols\":[\"WEB\",\"MOBILE\",\"CALL_CENTER\"]},\"doc\":\"Canal por el cual se confirmó la reserva\"},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ReservaConfirmada> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReservaConfirmada> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ReservaConfirmada> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ReservaConfirmada> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ReservaConfirmada> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ReservaConfirmada to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ReservaConfirmada from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ReservaConfirmada instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ReservaConfirmada fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Identificador único del evento */
  private java.lang.CharSequence eventId;
  /** Identificador de la reserva */
  private java.lang.CharSequence reservationId;
  /** Fecha de confirmación de la reserva */
  private java.time.Instant fechaConfirmacion;
  /** Canal por el cual se confirmó la reserva */
  private org.yasmani.avro.reserva.v1.CanalConfirmacion canalConfirmacion;
  private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReservaConfirmada() {}

  /**
   * All-args constructor.
   * @param eventId Identificador único del evento
   * @param reservationId Identificador de la reserva
   * @param fechaConfirmacion Fecha de confirmación de la reserva
   * @param canalConfirmacion Canal por el cual se confirmó la reserva
   * @param metadata The new value for metadata
   */
  public ReservaConfirmada(java.lang.CharSequence eventId, java.lang.CharSequence reservationId, java.time.Instant fechaConfirmacion, org.yasmani.avro.reserva.v1.CanalConfirmacion canalConfirmacion, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata) {
    this.eventId = eventId;
    this.reservationId = reservationId;
    this.fechaConfirmacion = fechaConfirmacion.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.canalConfirmacion = canalConfirmacion;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return reservationId;
    case 2: return fechaConfirmacion;
    case 3: return canalConfirmacion;
    case 4: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: reservationId = (java.lang.CharSequence)value$; break;
    case 2: fechaConfirmacion = (java.time.Instant)value$; break;
    case 3: canalConfirmacion = (org.yasmani.avro.reserva.v1.CanalConfirmacion)value$; break;
    case 4: metadata = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return Identificador único del evento
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * Identificador único del evento
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'reservationId' field.
   * @return Identificador de la reserva
   */
  public java.lang.CharSequence getReservationId() {
    return reservationId;
  }


  /**
   * Sets the value of the 'reservationId' field.
   * Identificador de la reserva
   * @param value the value to set.
   */
  public void setReservationId(java.lang.CharSequence value) {
    this.reservationId = value;
  }

  /**
   * Gets the value of the 'fechaConfirmacion' field.
   * @return Fecha de confirmación de la reserva
   */
  public java.time.Instant getFechaConfirmacion() {
    return fechaConfirmacion;
  }


  /**
   * Sets the value of the 'fechaConfirmacion' field.
   * Fecha de confirmación de la reserva
   * @param value the value to set.
   */
  public void setFechaConfirmacion(java.time.Instant value) {
    this.fechaConfirmacion = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'canalConfirmacion' field.
   * @return Canal por el cual se confirmó la reserva
   */
  public org.yasmani.avro.reserva.v1.CanalConfirmacion getCanalConfirmacion() {
    return canalConfirmacion;
  }


  /**
   * Sets the value of the 'canalConfirmacion' field.
   * Canal por el cual se confirmó la reserva
   * @param value the value to set.
   */
  public void setCanalConfirmacion(org.yasmani.avro.reserva.v1.CanalConfirmacion value) {
    this.canalConfirmacion = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return The value of the 'metadata' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * @param value the value to set.
   */
  public void setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.metadata = value;
  }

  /**
   * Creates a new ReservaConfirmada RecordBuilder.
   * @return A new ReservaConfirmada RecordBuilder
   */
  public static org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder newBuilder() {
    return new org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder();
  }

  /**
   * Creates a new ReservaConfirmada RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReservaConfirmada RecordBuilder
   */
  public static org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder newBuilder(org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder other) {
    if (other == null) {
      return new org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder();
    } else {
      return new org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder(other);
    }
  }

  /**
   * Creates a new ReservaConfirmada RecordBuilder by copying an existing ReservaConfirmada instance.
   * @param other The existing instance to copy.
   * @return A new ReservaConfirmada RecordBuilder
   */
  public static org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder newBuilder(org.yasmani.avro.reserva.v1.ReservaConfirmada other) {
    if (other == null) {
      return new org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder();
    } else {
      return new org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder(other);
    }
  }

  /**
   * RecordBuilder for ReservaConfirmada instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReservaConfirmada>
    implements org.apache.avro.data.RecordBuilder<ReservaConfirmada> {

    /** Identificador único del evento */
    private java.lang.CharSequence eventId;
    /** Identificador de la reserva */
    private java.lang.CharSequence reservationId;
    /** Fecha de confirmación de la reserva */
    private java.time.Instant fechaConfirmacion;
    /** Canal por el cual se confirmó la reserva */
    private org.yasmani.avro.reserva.v1.CanalConfirmacion canalConfirmacion;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.reservationId)) {
        this.reservationId = data().deepCopy(fields()[1].schema(), other.reservationId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.fechaConfirmacion)) {
        this.fechaConfirmacion = data().deepCopy(fields()[2].schema(), other.fechaConfirmacion);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.canalConfirmacion)) {
        this.canalConfirmacion = data().deepCopy(fields()[3].schema(), other.canalConfirmacion);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.metadata)) {
        this.metadata = data().deepCopy(fields()[4].schema(), other.metadata);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ReservaConfirmada instance
     * @param other The existing instance to copy.
     */
    private Builder(org.yasmani.avro.reserva.v1.ReservaConfirmada other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reservationId)) {
        this.reservationId = data().deepCopy(fields()[1].schema(), other.reservationId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.fechaConfirmacion)) {
        this.fechaConfirmacion = data().deepCopy(fields()[2].schema(), other.fechaConfirmacion);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.canalConfirmacion)) {
        this.canalConfirmacion = data().deepCopy(fields()[3].schema(), other.canalConfirmacion);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.metadata)) {
        this.metadata = data().deepCopy(fields()[4].schema(), other.metadata);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * Identificador único del evento
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * Identificador único del evento
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * Identificador único del evento
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * Identificador único del evento
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reservationId' field.
      * Identificador de la reserva
      * @return The value.
      */
    public java.lang.CharSequence getReservationId() {
      return reservationId;
    }


    /**
      * Sets the value of the 'reservationId' field.
      * Identificador de la reserva
      * @param value The value of 'reservationId'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder setReservationId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.reservationId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reservationId' field has been set.
      * Identificador de la reserva
      * @return True if the 'reservationId' field has been set, false otherwise.
      */
    public boolean hasReservationId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reservationId' field.
      * Identificador de la reserva
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder clearReservationId() {
      reservationId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaConfirmacion' field.
      * Fecha de confirmación de la reserva
      * @return The value.
      */
    public java.time.Instant getFechaConfirmacion() {
      return fechaConfirmacion;
    }


    /**
      * Sets the value of the 'fechaConfirmacion' field.
      * Fecha de confirmación de la reserva
      * @param value The value of 'fechaConfirmacion'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder setFechaConfirmacion(java.time.Instant value) {
      validate(fields()[2], value);
      this.fechaConfirmacion = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaConfirmacion' field has been set.
      * Fecha de confirmación de la reserva
      * @return True if the 'fechaConfirmacion' field has been set, false otherwise.
      */
    public boolean hasFechaConfirmacion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'fechaConfirmacion' field.
      * Fecha de confirmación de la reserva
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder clearFechaConfirmacion() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'canalConfirmacion' field.
      * Canal por el cual se confirmó la reserva
      * @return The value.
      */
    public org.yasmani.avro.reserva.v1.CanalConfirmacion getCanalConfirmacion() {
      return canalConfirmacion;
    }


    /**
      * Sets the value of the 'canalConfirmacion' field.
      * Canal por el cual se confirmó la reserva
      * @param value The value of 'canalConfirmacion'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder setCanalConfirmacion(org.yasmani.avro.reserva.v1.CanalConfirmacion value) {
      validate(fields()[3], value);
      this.canalConfirmacion = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'canalConfirmacion' field has been set.
      * Canal por el cual se confirmó la reserva
      * @return True if the 'canalConfirmacion' field has been set, false otherwise.
      */
    public boolean hasCanalConfirmacion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'canalConfirmacion' field.
      * Canal por el cual se confirmó la reserva
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder clearCanalConfirmacion() {
      canalConfirmacion = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.metadata = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'metadata' field.
      * @return This builder.
      */
    public org.yasmani.avro.reserva.v1.ReservaConfirmada.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReservaConfirmada build() {
      try {
        ReservaConfirmada record = new ReservaConfirmada();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.reservationId = fieldSetFlags()[1] ? this.reservationId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.fechaConfirmacion = fieldSetFlags()[2] ? this.fechaConfirmacion : (java.time.Instant) defaultValue(fields()[2]);
        record.canalConfirmacion = fieldSetFlags()[3] ? this.canalConfirmacion : (org.yasmani.avro.reserva.v1.CanalConfirmacion) defaultValue(fields()[3]);
        record.metadata = fieldSetFlags()[4] ? this.metadata : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReservaConfirmada>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReservaConfirmada>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReservaConfirmada>
    READER$ = (org.apache.avro.io.DatumReader<ReservaConfirmada>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (eventId == null ? 0 : eventId.hashCode());
    result = 31 * result + (reservationId == null ? 0 : reservationId.hashCode());
    result = 31 * result + (fechaConfirmacion == null ? 0 : fechaConfirmacion.hashCode());
    result = 31 * result + (canalConfirmacion == null ? 0 : ((java.lang.Enum) canalConfirmacion).ordinal());
    result = 31 * result + (metadata == null ? 0 : metadata.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ReservaConfirmada)) {
      return false;
    }
    ReservaConfirmada other = (ReservaConfirmada) o;
    if (Utf8.compareSequences(this.eventId, other.eventId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.reservationId, other.reservationId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.fechaConfirmacion, other.fechaConfirmacion)) {
      return false;
    }
    if (!java.util.Objects.equals(this.canalConfirmacion, other.canalConfirmacion)) {
      return false;
    }
    if (!java.util.Objects.equals(this.metadata, other.metadata)) {
      return false;
    }
    return true;
  }
}










